Created page component
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #10
Opened 2023-03-17 12:15 UTC by EvgeniyGartsev

2023-03-17 12:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 15:17 UTC, GSemikozov requested changes

2023-03-17 15:17 UTC, GSemikozov commented on components/component/component.css
> +  padding: 36px 165px 166px 165px;
слева-справа - лишнее, мы ведь для этих целей используем container

2023-03-17 15:17 UTC, GSemikozov commented on components/component/component.css
> +  grid-template-columns: 1fr 4fr;
auto 1fr

2023-03-17 15:17 UTC, GSemikozov commented on components/component/component.css
> +  width: 825px;
фиксировать ширину и высоту не надо

2023-03-17 15:17 UTC, GSemikozov commented on components/content/content.css
>      height: 200px;
лишнее, высоту удалим

2023-03-18 21:36 UTC, GSemikozov requested changes

2023-03-18 21:36 UTC, GSemikozov commented on components/component/component.css
> +  grid-template-columns: auto 4fr;
auto 1fr

2023-03-20 09:46 UTC, GSemikozov approved these changes

2023-03-20 09:46 UTC, merged