Added calendar
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #11
Opened 2023-03-17 14:27 UTC by EvgeniyGartsev

2023-03-17 14:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 15:16 UTC, GSemikozov requested changes

2023-03-17 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px 30px;
`28px 26px 32px`

2023-03-17 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  text-align: center;
на уровне блока - лишнее

2023-03-17 15:16 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__title {
можно тут

2023-03-18 05:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-18 06:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-18 21:36 UTC, GSemikozov approved these changes

2023-03-18 21:36 UTC, merged