Adapted pages and added logo
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #17
Opened 2023-03-21 08:25 UTC by EvgeniyGartsev

2023-03-21 08:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-22 11:56 UTC, GSemikozov requested changes

2023-03-22 11:56 UTC, GSemikozov commented on components/component/component.css
> +    font-family: 'Inter';
переписывать неизменяемые свойства не нужно?

2023-03-22 11:56 UTC, GSemikozov commented on components/component/component.css
> +  .component__container > :first-child {
точно ли нужно именно так делать? а если структура поменяется? или не поменяется?

2023-03-22 12:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 07:53 UTC, GSemikozov approved these changes

2023-03-24 07:53 UTC, merged