Added input
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #21
Opened 2023-03-24 13:29 UTC by EvgeniyGartsev

2023-03-24 13:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-24 17:49 UTC, GSemikozov requested changes

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <fieldset class="input-fieldset">
fieldset - лишнее, используется для компановки нескольких инпутов по предназначению

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <legend class="input-fieldset__legend">Label</legend>
label

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="input-fieldset__label">
а инпут в данном случае заворачивать в label не надо

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="input-fieldset__label">
но - надо завернуть инпут и иконки в общий враппер, чтобы они позиционировались только с учетом высоты инпута (безотносительно label)

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  padding-left: 24px;
паддинги со всех сторон

2023-03-24 17:49 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input-fieldset__input_invalid,
классы-модификаторы состояния блока реализуем на уровне блока, а на уровне компонентов стили меняются так: .input-fieldset_invalid .input-fieldset__input {}

2023-03-25 08:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-25 13:55 UTC, GSemikozov approved these changes

2023-03-25 13:56 UTC, merged