Almost completed project
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #29
Opened 2023-04-09 18:25 UTC by EvgeniyGartsev

2023-04-09 18:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-14 09:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-14 09:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-16 20:06 UTC, GSemikozov requested changes

2023-04-16 20:06 UTC, GSemikozov commented on assets/scripts/preload.js
> +$(window).load(function() {
у нас же вроде не подключен jquery, это разве работает?

2023-04-17 13:27 UTC, EvgeniyGartsev commented on assets/scripts/preload.js
> +$(window).load(function() {
на самой странице подключен так <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>

2023-05-07 11:45 UTC, GSemikozov approved these changes

2023-05-07 11:45 UTC, merged