Added cards on main page
js-tasks-ru/htmlcss-20230227_evgeniy-gartsev pull request #9
Opened 2023-03-16 14:55 UTC by EvgeniyGartsev

2023-03-16 14:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-16 16:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 16:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-16 21:44 UTC, GSemikozov requested changes

2023-03-16 21:44 UTC, GSemikozov commented on index.html
> +        <div class="container content__container">
мешать с блоком container не надо, content__container лучше расположить внутри

2023-03-16 21:44 UTC, GSemikozov commented on components/content/content.css
> +.content__title {
это все-таки тайтл не контента, а карточки, так что - .content__card-title. А еще лучше - вынести карточку как отдельный блок

2023-03-17 09:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-03-17 09:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-03-17 15:11 UTC, GSemikozov approved these changes

2023-03-17 15:11 UTC, merged